Feat: migrate SendGrid Email functionality from Layyun to Cloudflare Worker.
h8r-dev/heighliner-website pull request #141
Opened 2022-06-08 09:46 UTC by Penggeor

2022-06-08 10:02 UTC, 92hackers requested changes

2022-06-13 11:57 UTC, Penggeor commented
Get a try: http://43.154.10.129:3000/contact-us

2022-06-13 12:14 UTC, hongchaodeng commented
I just sent a message. Where does it go?

2022-06-13 13:40 UTC, Penggeor commented
> I just sent a message. Where does it go?

Oh, my mistake, it is sent to my email. I have changed to contact@h8r.io, try again. @hongchaodeng

2022-06-14 03:25 UTC, 92hackers approved these changes

2022-06-14 03:25 UTC, merged