Feat: Slogan section v2
h8r-dev/heighliner-website pull request #19
Opened 2022-04-24 11:51 UTC by Penggeor

2022-04-24 11:52 UTC, Penggeor commented
#20

2022-04-25 03:11 UTC, 92hackers requested changes

2022-04-25 03:11 UTC, 92hackers commented on src/css/custom.css
> +  font-family: face;
`font-family: face;`, what's this ?

2022-04-26 01:13 UTC, Penggeor commented on src/css/custom.css
> +  font-family: face;
This is mistake.

2022-04-27 02:20 UTC, 92hackers commented on src/utils/MathPlus.ts
> +  switch (true) {
```javascript
if (value < min) return min
if (value > max) return max
return value
```

2022-04-30 02:29 UTC, merged